import { apiSuccessEnvelope } from "@/lib/api-response";
import { withApiAuth } from "@/lib/auth";

/**
 * Placeholder for future server-side semantic patches (Mastra / Gemini).
 * Deterministic Sharingan patches are produced locally: `pi validate --format patches` and `pi fix`.
 */
export const POST = withApiAuth(async (request) => {
  const requestId = request.requestId;
  await request.json().catch(() => ({}));
  const res = apiSuccessEnvelope({
    data: {
      patches: [] as unknown[],
      note:
        "Deterministic AST patches are generated by the CLI (`pi validate --format patches`, `pi fix`).",
    },
    object: "pi_cli_validate_patches",
    requestId,
    status: "completed",
    httpStatus: 200,
  });
  res.headers.set("X-Request-Id", requestId);
  return res;
});
