import { z } from 'zod';

import { campaignAdOutputSchema } from './campaign-ads-api.js';

/**
 * Edit request for images generated by:
 * - `POST /api/v1/campaigns/generate` (job type: `campaign_ad_generation`)
 */
export const campaignAdEditInputSchema = z.object({
  /**
   * The canonical provenance identifier for the source image.
   * Must be a `campaign_ad_generation` job id previously returned by `campaigns/generate`.
   */
  source_job_id: z.string().uuid(),

  /** What to change in the existing image (instruction prompt). */
  prompt: z.string().trim().min(1).max(5000),

  /** Optional extra references to guide the edit (https URL or base64/data URL). */
  reference_images: z.array(z.string().min(1)).max(6).optional(),

  /** Optional brand id to reinforce the existing brand identity during edits. */
  brand_id: z.string().uuid().optional(),

  /** Optional output configuration (aspect ratio, resolution, thinking intensity). */
  output: campaignAdOutputSchema.optional(),

  /** Optional developer-provided correlation id. */
  client_reference_id: z.string().trim().min(1).max(200).optional(),

  /**
   * Optional tracing metadata echoed in the job payload.
   * Max 16 key/value pairs, each value <= 500 chars.
   */
  metadata: z
    .record(z.string().trim().max(500))
    .refine((value) => Object.keys(value).length <= 16, {
      message: 'metadata may contain at most 16 keys.',
    })
    .optional(),
});

export type CampaignAdEditInput = z.infer<typeof campaignAdEditInputSchema>;
